In [1]:
import pandas as pd
import json

In [2]:
data = json.load(open("data/mpd.slice.0-999.json"))
df = pd.DataFrame(data["playlists"])

In [3]:
df

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,old,false,995,1507852800,41,40,1,"[{'pos': 0, 'artist_name': 'Katrina', 'track_u...",8,9917901,36,NaN
996,Daze,false,996,1479254400,17,17,1,"[{'pos': 0, 'artist_name': 'PARTYNEXTDOOR', 't...",13,3699248,15,NaN
997,rap,false,997,1410307200,119,98,1,"[{'pos': 0, 'artist_name': 'LoveRance', 'track...",63,27538723,82,NaN
998,Country,false,998,1507939200,108,75,1,"[{'pos': 0, 'artist_name': 'Hunter Hayes', 'tr...",37,24950143,40,NaN
999,thinking of you,false,999,1507766400,44,43,1,"[{'pos': 0, 'artist_name': 'Pvris', 'track_uri...",34,9065801,37,NaN

In [5]:
df["tracks"]
# die tracks sind einzelne Dictonaries im "playlists"-dictonary

0      [{'pos': 0, 'artist_name': 'Missy Elliott', 't...
1      [{'pos': 0, 'artist_name': 'Survivor', 'track_...
2      [{'pos': 0, 'artist_name': 'Hoody', 'track_uri...
3      [{'pos': 0, 'artist_name': 'Camille Saint-Saën...
4      [{'pos': 0, 'artist_name': 'The Smashing Pumpk...
                             ...
995    [{'pos': 0, 'artist_name': 'Katrina', 'track_u...
996    [{'pos': 0, 'artist_name': 'PARTYNEXTDOOR', 't...
997    [{'pos': 0, 'artist_name': 'LoveRance', 'track...
998    [{'pos': 0, 'artist_name': 'Hunter Hayes', 'tr...
999    [{'pos': 0, 'artist_name': 'Pvris', 'track_uri...
Name: tracks, Length: 1000, dtype: object